language: scala
scala:
  - 2.10.6

jdk:
  - oraclejdk8

script:
  - sbt "setupTests" "Test210:test" "Test211:test" "Test212:test"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/booe

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete
