language: scala

jdk:
  - oraclejdk8

stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)

before_install:
  - if [ $TRAVIS_PULL_REQUEST = 'false' ]; then
    openssl aes-256-cbc -K $encrypted_5342f3bad2a7_key -iv $encrypted_5342f3bad2a7_iv -in travis/secrets.tar.enc -out travis/local.secrets.tar -d;
    tar xv -C travis -f travis/local.secrets.tar;
    fi

jobs:
  include:
    - stage: test
      script:
        - bin/scalafmt --test

    - stage: test
      script:
        - sbt "setupTests" "Test210:test" "Test211:test" "Test212:test"

    - stage: release
      script:
        - sbt "errorsSummary/releaseEarly"

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/launchers
    - $HOME/.sbt/boot

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

env:
  global:
    - secure: 0uxipnVh39YUjdwcXXvdi8s/N2gsMohDwyFWWxsajPsUGP/4g5Cc0QVadRazMhCZaZA9uZqADyYc+qdl5ExL3GdYomcZlcHYJjZaAQ2yScYrASUZuo9a7WgKwehlLpYmJ8QsnjLiaYtVuk7/X7z2x4ZezzrQUoonYeo7syZUjXx6qG2xlP8BlgO2op8NgvXso3ecNMXj4FyWRXi0vCZnXvSwiOSuNCR2aObsDMMNZlt+5JS3nCKISkyvdVx359uV7yq8Gqcwz9/DbnwGwDkohgo0VNuHKVz4v712HrnSg6ybaVsmyNdOHi9XKGKXzWtq7YyGAFE45g3m33ivkqT8lNG9ZFyQdLJBiYK8nSQChnfSnvkMOOqS+a2BD8AV631mL1S0u17hP1lHAS6hQX2p/4Qls7EsoboIEzY8QGWzL2R752zI2y0zmVNHYVhMHelzJv9fBcG3D0UB9t6eU4zKNXMblJchkAIuPaOFoKIyDOM6nsOkl+7PLu2ArKlMyX9imMwdyUcl45nQ0fmUUMbvYMyHDhuUXccIYYPXbKec+Jy5prld7pEjO2jRU4IZL1Y7KZSLQ8jEpwG4V3BRvTgg9D+lyxnBK2rxYcB0ApXXe9WF36Rdjv/FF/NiRRip73E39DeRGBuSz5dJAUmIvw0A2iEuJZL/UwzwKPR5VuRoXXA=
    - secure: dS7hBqhcUHX5umKQwWAcsatjh7UvSaT5S6yF2hKoU0fW+rH/rizmN7O7bfrRt1U04/i+MpWIxPUaV2SxWqqOkybfiB0oTW2p9xXzIeB8fLbNv+SUZyFSZTUuaiYX83hvQNM6tYs7zTdtaiq1ykO5jn6aszhiAjGg5XYq561ysQuka0Vvnq/JqnQbx8ypVkP0TsOX5XOW9ApbfGbaXTyJg3XZSZrOoUvHebyxXo74uQ10zRryCLaMKWi1VtpHyyv7f77+pLlBXn/Tj8YyIGBDvp2impY5jQp+lteLUvlLLqmIAmpB5Tu6NKGgYyVcigR6WtzYM73gow6BgzfBWsNiIgn3xPbzGUyuyXGDUq0UUaAM8Wtuz/BbQKjo/a4pAgl5zF6yQn0MMqZCYBK+U6lzV7xI1YVRHybDngCJIFRrrlE4vNp/tDgVLOts7YK2MwmeSx57XOUEE+zIISJ2PStRDbGBdmNfUjf/K1Nhcbg0xtTX8Qp+QdruLs3V+yXoMbQxTZXPWcRjHIJFe9vETmXBQTEBbP66pGNS51faUo+G4JvmmBHWKqnuDNBXIhIKPQRBdazi0bu2egKvborGkVw1lteDNThFPMaa4yQsx9tLdoxTXkbdZI0oxhIQgcSwkVvkAf2RcimPYUKj41Jr1cM5Yd3Rvc7A0pWjVDryX0rmd78=
    - secure: aRh9oPx6/m8Hf1I490borxdWXl6dQfrMVz3v4xuEvoeSxRE4PIXW2zCybEMttHcAIN6wzPD0VidQp9rRFJH790dUCQFR9scGzrAd/kK2SQneoRZOQOytw+QJoDGZowmK3jkoiQvZvYm6aKKvwGW9kX7A7aNLHG2pDvb1vBXjIhumFRWa/eofS63riYJ7JHw+00RkmUjco+wdZjtMRSOKxUB1WwpL9EoNEnmo7K6yL0ILYlc1ixUAKlU7D0LahhGEsguokpaV6rIN905nsndnn35zwcIPDQyMZEFpVvLA98E8cPlC99jsI4eKMTKVnI8ENnHP0KF/0Zfw+SsrTxFOazI+f6f/VXr159CAECJ/uFvM6aDeBEG4DtXASMaoDbKPw/Hn7HFmR5rIG9K1V0t6sdzTOGsJN1K3G1hw0gOgGPSbwDP9gbcPCxvuTZsu8Smcrc5Vco76MRXh0GBb3jUsGG2At/QmuBOnz1eBAztbcuqzjch+b8CbUs2Iuy0/V7soRmMhPpL3AVtc5lXMCqp6xXb27oVGdGuLtEP7n6XRmkzksP4FEKEoE45pRsQEdHBcl2dWYR+drlnLcTL/LDcotBYKFWfMlHVFPB2KDi4WfWn9LIIBWU0jcRu3xmEWKrqdBWrE65KOhht8AjCc4PCHZjjNUN48Eu/QqhEGsYrOQ3I=
