addSbtPlugin("com.jsuereth"      % "sbt-pgp"           % "1.1.1")
addSbtPlugin("org.foundweekends" % "sbt-bintray"       % "0.5.4")
addSbtPlugin("org.scala-sbt"     % "sbt-contraband"    % "0.4.1")
addSbtPlugin("ch.epfl.scala"     % "sbt-release-early" % "2.1.1")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"      % "0.9.19")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"      % "2.4.0")
