name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: olafurpg/setup-scala@v10
    - run: sbt "setupTests" "Test210:test" "Test211:test" "Test212:test"
